site_name: Engineering Notebook
site_url: https://LADransfield.github.io
site_author: Lauren Dransfield
site_description: Mechanical engineering notes 

nav:
  - Home: index.md
  - Mathematics: mathematics.md
  - Fluid Mechanics: fluidMechanics.md
  # - Solid Mechanics: solidMechanics.md
  # - Thermodynamics: thermodynamics.md
  # - Electronics: electronics.md
  # - Materials: materials.md
  # - Manufacturing: manufacturing.md
  - Computational Fluid Dynamics: computationalFluidDynamics.md
  # - Finite Element Analysis: finiteElementAnalysis.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - C
    - C++
    - matlab

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - styles/sectionnumbers.css
  - styles/style.css